# -*- coding: utf-8 -*-
"""Rendimiento Anual Compuesto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dt0TgVf5QfmrhD12iESspF-AO9o9LtAH
"""

rendimientos_anual = [10.38, 10.01, 9.69]  # en porcentaje

# Convertimos a decimal mensual
rendimientos_mensual = [r / 100 / 12 for r in rendimientos_anual]

# Interés compuesto acumulado
acumulado = 1
for r in rendimientos_mensual:
    acumulado *= (1 + r)

# Rendimiento anualizado del período
rendimiento_acumulado_anualizado = (acumulado ** (12 / len(rendimientos_mensual))) - 1
rendimiento_periodo_real = acumulado - 1

print(f"🔁 Rendimiento real del período: {rendimiento_periodo_real * 100:.2f}%")
print(f"📈 Rendimiento anualizado acumulado: {rendimiento_acumulado_anualizado * 100:.2f}%")